# https://taskfile.dev

version: '3'

vars:

tasks:
  build-zd:
    dir: src/cmd
    cmds:
      - go build -o main -buildvcs=false

  run-zd:
    dir: src/cmd
    cmds:
      - go run main.go

  run-zd-dev:
    dir: src/cmd
    cmds:
      - air
  
  run-us:
    dir: mockUserService
    cmds:
      - json-server --config json-server.json --routes routes.json --watch db.json

