# https://taskfile.dev
version: '3'

vars:

tasks:
  build-zd:
    dir: cmd/app
    cmds:
      - go build -o main -buildvcs=false

  run-zd:
    dir: cmd/app
    cmds:
      - go run main.go

  run-zd-dev:
    dir: cmd/app
    cmds:
      - air
  
  run-con:
    dir: cmd/consumer
    cmds:
      - go run main.go
  
  run-us:
    dir: mockUserService
    cmds:
      - json-server --config json-server.json --routes routes.json --watch db.json

