version: "3.8"

services:
  devcontainer:
    container_name: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      - ENV=${ENV}
      - PORT=${PORT}

    volumes:
      - ..:/workspaces:cached

    command: sleep infinity
